security:

    providers:
        our_db_provider:
            entity:
                class: App\Entity\Utilisateur
                property: pseudo

    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login
    encoders:
        App\Entity\Utilisateur:
            algorithm: bcrypt

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/%, roles: ROLE_USER}

